Feature/kas 2308 refactor newsletter service
kanselarij-vlaanderen/newsletter-service pull request #39
Opened 2021-12-20 14:05 UTC by TaneeG

Jira: https://kanselarij.atlassian.net/browse/KAS-2308
Frontend:

2021-12-21 15:32 UTC, ValenberghsSven reviewed
De errors komen niet goed door naar frontend (zie frontend PR voor detail).
Niet zeker of dat hier moet aangepast worden of in frontend.

2022-01-03 10:34 UTC, MikiDi commented
Er lijkt hier veel meer aan indentatie veranderd dan ik zou verwachten. @TaneeG kan je meteen een `.editorconfig`-file toevoegen met een `*.js`-rule gelijkaardig aan [deze](https://github.com/kanselarij-vlaanderen/frontend-kaleidos/blob/development/.editorconfig#L9)? Dan kan dit in de toekomst niet meer gebeuren.

2022-01-04 11:50 UTC, erikap requested changes
Deze service stamt nog uit de early-Kaleidos days en heeft volgens mij meer liefde en een grovere refactor nodig dan nu in deze PR het geval is om hem op een beter niveau te krijgen. Elke lijn code moet bij wijze van spreken kritisch bekeken worden, begrepen worden en in vraag gesteld worden of ze effectief nut heeft.

Voor het Vlivia-project zijn er 2 services gemaakt met gelijkaardige integratie-functionaliteit met Belga/Mailchimp die als inspiratie kunnen dienen (en waar zelfs stukken integratie-code van herbruikt kunnen worden):
- https://github.com/kanselarij-vlaanderen/press-releases-belga-publication-service
- https://github.com/kanselarij-vlaanderen/press-releases-mailchimp-publication-service

Zaken die ik zo direct zie (naast de inline code review):
- dependencies die niet gebruikt worden, overbodig zijn wegens reeds voorzien door de javascript-template of geen meerwaarde hebben (vb. `cors`, `dotenv`, `express`, ...)
- onvolledige metadata in `package.json`
- nieuwe versie van de javascript-template beschikbaar
- outdated syntax in `Dockerfile`
- ontbreken van een README met minimale documentatie van de env variables en API endpoints. Er zijn [voorbeelden van services](https://github.com/kanselarij-vlaanderen/press-releases-mailchimp-publication-service) die het geprefereerde README formaat volgen

2022-01-04 11:50 UTC, erikap commented on .babelrc
> +        "@babel/plugin-transform-modules-commonjs"
Is deze plugin effectief nodig?

2022-01-04 11:50 UTC, erikap commented on .gitignore
> +package-lock.json
`package-lock.json` enkel toevoegen aan de `.gitignore` file heeft geen zin. Dan gaat de repository een outdated `package-lock.json` bevatten. 
De file moet ook verwijderd worden uit de git repos én het automatisch genereren van de lock file moet gedisabled worden ([voorbeeld](https://github.com/kanselarij-vlaanderen/press-releases-mailchimp-publication-service/blob/master/.npmrc))

2022-01-04 11:50 UTC, erikap commented on app.js
> +dotenv.config();
Overbodig. Er wordt in de praktijk geen `.env` file gebruikt maar enkel env vars die in de `docker-compose.yml` gezet worden.

2022-01-04 11:50 UTC, erikap commented on app.js
>    host
Host ook configureerbaar maken via env var (eventueel met de huidige waarde als default)

2022-01-04 11:50 UTC, erikap commented on app.js
> +app.use(bodyParser.json({type: 'application/*+json'}));
Is dit noodzakelijk?

2022-01-04 11:50 UTC, erikap commented on app.js
> +import {ok} from 'assert';
Deze library lijkt mij volledig verkeerd gebruikt te worden. [`assert.ok` wordt gebruikt om test assumpties te valideren](https://nodejs.org/api/assert.html#assertokvalue-message), terwijl het in deze implementatie als status code gebruikt wordt in de HTTP response. De library lijkt mij overbodig.

2022-01-04 11:50 UTC, erikap commented on app.js
> +import * as mailchimpService from "./repository/mailchimp-service";
Consequent gebruik van enkele quotes `'` voor imports

2022-01-04 11:50 UTC, erikap commented on app.js
> +      status: ok, statusCode: 201,
Bij succes wordt de status en status code niet mee teruggegeven in de response body in JSON:API.
Deze comment geldt op nog plaatsen in deze file.

2022-01-04 11:50 UTC, erikap commented on app.js
> +    res.send({
HTTP status `201` zetten op response bij het aanmaken van een nieuwe resource (niet in de body)

2022-01-04 11:50 UTC, erikap commented on app.js
> +app.post('/mail-campaign', async (req, res) => {
Meervoud gebruiken voor het path (zie [JSON:API spec](https://jsonapi.org/format/#crud-creating))

2022-01-04 11:50 UTC, erikap commented on app.js
> +      error: {
Errors moeten teruggeven worden in een `errors`-array (zie [JSON:API spec](https://jsonapi.org/format/#error-objects)). 
Je kan hier ook gebruik maken van de `errorHandler` die voorzien wordt door de javascript-template ([voorbeeld](https://github.com/kanselarij-vlaanderen/press-releases-acmidm-login-service/blob/339d32e1060d5a88d01d87e055bf2361fc4a7cfc/app.js#L68-L71))

Deze comment geldt voor alle error responses in deze file.

2022-01-04 11:50 UTC, erikap commented on app.js
> +  const campaignId = req.body.data.id;
Meer RESTful om het verzenden uit te drukken als een actie op 1 mail-campaign: `/mail-campaigns/:id/send`. Op die manier wordt de id meegegegeven in de URL ipv in de request body.

2022-01-04 11:50 UTC, erikap commented on app.js
> +        'type': 'mail-chimp-campaign',
Aangezien het hier over dezelfde soort resource gaat als bij het aanmaken/versturen van een mail-campaign, moet het type hetzelfde zijn als de andere endpoints.

2022-01-04 11:50 UTC, erikap commented on app.js
> +app.get('/mail-campaign/:id', async (req, res) => {
Meervoud gebruiken voor het path

2022-01-04 11:50 UTC, erikap commented on app.js
> +app.delete('/mail-campaign/:id', async (req, res) => {
Meervoud gebruiken voor het path

2022-01-04 11:50 UTC, erikap commented on app.js
> +    res.send({status: ok, statusCode: 200});
Status 204 terugsturen (zie [JSON:API spec](https://jsonapi.org/format/#crud-deleting-responses-204))

2022-01-04 11:50 UTC, erikap commented on app.js
> +app.get('/mail-campaign-content/:id', async (req, res) => {
Ik zou content als een relatie zien van het mail-campaign object: `/mail-campaigns/:id/content`

2022-01-04 11:50 UTC, erikap commented on app.js
> +        'type': 'mail-chimp-campaign',
Het gaat hier om een ander type resource dan de andere endpoints. Vb. `mail-campaign-content`

2022-01-04 11:50 UTC, erikap commented on app.js
> +  let meetingId = req.params.meeting - id;
Werkt dit!?
Autoformatting kan handig zijn, maar we moeten wel blijven nadenken...

2022-01-04 11:50 UTC, erikap commented on app.js
> +app.post('/belga', async (req, res) => {
JSON:API is resource oriented. Ik stel hier iets voor als `/belga-newsletters`

2022-01-04 11:50 UTC, erikap commented on app.js
> +    res.send({status: ok, statusCode: 200, data: {type: 'belga-campaign'}});
Status 201 voor het aanmaken van een nieuwe resource (en type aanpassen naar wat er in het request-path gebruikt wordt)

2022-01-04 11:50 UTC, erikap commented on app.js
> +    res.send({status: ok, statusCode: 200, data: {type: 'belga-campaign'}});
`id` ontbreekt in de response. Je zou hier bijvoorbeeld de naam van de gegenereerde file  (niet het volledige path) kunnen gebruiken.

2022-01-04 11:50 UTC, erikap commented on app.js
> +app.get('/belga/:meeting-id', async (req, res) => {
In lijn met vorig endpoint zou ik gaan voor `/belga-newsletters/:id`

2022-01-04 11:50 UTC, erikap commented on app.js
> +    });
Is dit nog nodig na de `res.download()`?

2022-01-04 11:50 UTC, erikap commented on app.js
> +  const meetingId = req.body.data.meetingId;
Om de body [JSON:API compliant](https://jsonapi.org/format/#crud-creating) te maken moet hier een mail-campaign resource gestuurd worden. De meeting kan volgens mij als een relatie van die mail-campaign resource aanzien worden.

2022-01-04 11:50 UTC, erikap commented on app.js
> +  const meetingId = req.body.data.meetingId;
Om de body [JSON:API compliant](https://jsonapi.org/format/#crud-creating) te maken moet hier een belga-newsletter resource gestuurd worden. De meeting kan volgens mij als een relatie van die belga-newsletter resource aanzien worden.

2022-01-10 09:55 UTC, erikap commented
In deze PR misschien best enkel focussen op het API gedeelte. Ik heb een nieuwe story gemaakt om de rest van de code aan te pakken.

2022-01-19 08:31 UTC, TaneeG commented on .babelrc
> +        "@babel/plugin-transform-modules-commonjs"
Deze laat ik voor de andere story

2022-01-19 08:31 UTC, TaneeG commented
@erikap Je mag deze nog eens herbekijken. Ik heb al een aanzet tot ReadMe toegevoegd.

2022-03-14 08:14 UTC, ValenberghsSven commented
Code overgenomen in https://github.com/kanselarij-vlaanderen/newsletter-service/pull/42. Ik sluit deze

2022-03-14 08:14 UTC, closed without merging