Feature/kas 3100 upgrade newsletter service
kanselarij-vlaanderen/newsletter-service pull request #42
Opened 2022-02-23 14:24 UTC by Annelies-P

2022-03-07 17:26 UTC, ValenberghsSven requested changes
Not done with review yet but wanted to close off the day with found issues.

Locally the connection to Belga was not happening for some reason and that error was not caught.
`Uncaught Error: connect ECONNREFUSED 127.0.0.1:21
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:131:14)
Emitted 'error' event on  instance at:
    at Socket.onerror (/usr/src/output/app/node_modules/ftp/lib/connection.js:280:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`
    
This error crashes the newsletter-service completely. Not sure how to reproduce (my credentials are correct)
Perhaps missing FTP_HOST?

2022-03-07 17:26 UTC, ValenberghsSven commented on README.md
> +| MAILCHIMP_FROM_NAME            | string | name to be used as sender details                            |
I have some tacit knowledge of the mailchimp services, not sure if we need/want to mention this in the readme or somewhere else:

1. In order for a mail to be sent from mailchimp, the "from" should be a validated domain. Validating that domain is something you need to do on the mailchimp interface/website. (a mail gets sent to you with a verify link)
2. `POST /mail-campaigns/:id/send` will not work if there are no subscribers to your content (no mails to send), in current implementation this is usually caused by not having any themes selected and therefore no mailchimp mails should be sent. But could also happen f.e. should you edit/remove the subscribers on the ACC mailchimp account.

2022-03-07 17:26 UTC, ValenberghsSven commented on app.js
> +    console.log('A problem occured when prepairing campaign in Mailchimp.');
typo "preparing"

2022-03-07 17:26 UTC, ValenberghsSven commented on app.js
> +    }
this exact block is used 4 times. Perhaps a `logErrorResponse` util?

2022-03-07 17:26 UTC, ValenberghsSven commented on app.js
> +      res.send({
should there be a `status(200)` in this case?

2022-03-07 17:26 UTC, ValenberghsSven commented on repository/belga-service.js
> +    const xmlConfig = createXMLConfig(escapedContent, sentAt, identicationDate, title);
typo "identificationDate"

2022-03-07 17:26 UTC, ValenberghsSven commented on repository/mailchimp-service.js
> +    console.log("Prepairing new campaign in Mailchimp...");
typo "preparing"

2022-03-07 17:26 UTC, ValenberghsSven commented on util/xml-renderer.js
> +                    {DateId: identicationDate},
typo "identificationDate", also in params (line 16) and further down (line 123)

2022-03-07 17:26 UTC, ValenberghsSven commented on README.md
> +| BELGA_FTP_HOST                 | string | the Belga server to connect to. Default value 'ftp.belga.be' |
Where is this default set?
I had to locally set `FTP_HOST` or the connection to belga would fail (I think, the connection issue was resolved after adding the host)
How does this work on PROD and ACC? There is no "FTP_HOST" env variable but the service connects to belga. Is that stored somewhere?

2022-03-15 13:24 UTC, Annelies-P commented on README.md
> +| MAILCHIMP_FROM_NAME            | string | name to be used as sender details                            |
Indeed, I bumped into those issues as well. I've added a comment in the readme to avoid other people having to dig into it one other time.

2022-03-15 13:24 UTC, Annelies-P commented on app.js
> +      res.send({
indeed, it has been added now

2022-03-15 13:28 UTC, Annelies-P commented on README.md
> +| BELGA_FTP_HOST                 | string | the Belga server to connect to. Default value 'ftp.belga.be' |
The default value was not set, this has been corrected now.
There used to be a default value, but it was lost during the refactoring.

2022-03-17 15:33 UTC, ValenberghsSven approved these changes

2022-03-18 10:21 UTC, merged